export const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    SLOW_MOTION_SCALE: 0.2,
    MAX_DIFFICULTY: 5,
    DIFFICULTY_RAMP: 0.01,
    COMET_SPAWN_DIST: 600,
    COMET_SPEED_MIN: 100,
    COMET_SPEED_RANGE: 50,
    LAUNCH_SCALE: 0.05,
    DESPAWN_DISTANCE: 1500,
    COMET_SCORE: 100
};
