export const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    TILE_SIZE: 60,
    PARTICLE_SPAWN_RATE: 0.3,
    PARTICLE_SPEED: 50,
    PARTICLE_LIFE: 1.0,
    WIN_TRANSITION_DELAY: 1000
};
