export const CONFIG = {
    CANVAS_WIDTH: 480,
    CANVAS_HEIGHT: 600,
    GAME_WIDTH: 300,
    COLS: 10,
    ROWS: 20,
    BLOCK_SIZE: 30,
    INITIAL_DROP_INTERVAL: 1000,
    DROP_SPEED_FACTOR: 0.9,
    LINES_PER_LEVEL: 5,
    SINGLE_LINE_SCORE: 100,
    TOUCH_TAP_THRESHOLD: 20,
    TOUCH_TAP_TIME: 300,
    SWIPE_THRESHOLD: 30,
    HARD_DROP_THRESHOLD: 50
};
