import { DIRS } from 'rot-js';

/**
 * Monster entity generated by MonsterFactory's DNA system.
 */
export class Monster {
  constructor(config) {
    this.type = 'monster';
    this.name = config.name || 'Unknown';
    this.x = config.x || 0;
    this.y = config.y || 0;
    this.alive = true;
    this.frozen = false;
    this.alerted = false;

    // Body type
    this.bodyType = config.bodyType;
    this.glyph = config.glyph || '?';

    // Stats (already scaled by DTL)
    this.stats = {
      hp: config.hp,
      maxHP: config.hp,
      atk: config.atk,
      def: config.def,
      xp: config.xp || 0
    };

    // Element
    this.element = config.element || null;
    this.resistances = { ...config.resistances };

    // Behavior
    this.behavior = config.behavior || 'wander';
    this.defaultBehavior = config.behavior || 'wander';

    // Abilities
    this.abilities = config.abilities || [];
    this.abilityCooldowns = {};

    // Visual
    this.color = config.color || '#ff6600';
    this.tier = config.tier || 1;
    this.isElite = config.isElite || false;
    this.isChampion = config.isChampion || false;

    // Status effects
    this.statusEffects = new Map();

    // AI state
    this.targetX = null;
    this.targetY = null;
    this.patrolPath = [];
    this.patrolIndex = 0;
    this.lastSeenPlayerX = null;
    this.lastSeenPlayerY = null;

    // Loot
    this.lootTier = config.lootTier || 'common';
    this.credits = config.credits || 3;
  }

  getWeapon() {
    return {
      atk: this.stats.atk,
      element: this.element || 'kinetic',
      durability: Infinity,
      affixes: [],
      silent: false
    };
  }

  takeDamage(amount, source) {
    this.stats.hp -= amount;
    if (this.stats.hp <= 0) {
      this.stats.hp = 0;
      this.alive = false;
      return true;
    }
    // Taking damage alerts and switches to hunt
    this.alerted = true;
    if (this.behavior !== 'flee') this.behavior = 'hunt';
    return false;
  }

  heal(amount) {
    this.stats.hp = Math.min(this.stats.maxHP, this.stats.hp + amount);
  }

  takeTurn(game) {
    if (!this.alive || this.frozen) {
      this.frozen = false;
      return;
    }

    // Process status effects
    game.combatSystem.processStatusEffects(this);
    if (!this.alive) return;

    // Check flee threshold
    if (this.stats.hp / this.stats.maxHP < 0.3 && this.defaultBehavior !== 'guard') {
      this.behavior = 'flee';
    }

    // Process abilities
    this.processAbilities(game);

    // Process regeneration ability
    for (const ability of this.abilities) {
      if (ability.name === 'Regeneration') {
        const scaling = this.getAbilityScaling(ability, game.dtl);
        this.heal(scaling.hpPerTurn || 1);
      }
    }

    // Execute behavior
    switch (this.behavior) {
      case 'hunt': this.doHunt(game); break;
      case 'patrol': this.doPatrol(game); break;
      case 'wander': this.doWander(game); break;
      case 'flee': this.doFlee(game); break;
      case 'guard': this.doGuard(game); break;
      default: this.doWander(game); break;
    }
  }

  processAbilities(game) {
    for (const ability of this.abilities) {
      const cdKey = ability.name;
      if (this.abilityCooldowns[cdKey] > 0) {
        this.abilityCooldowns[cdKey]--;
      }
    }
  }

  getAbilityScaling(ability, dtl) {
    if (!ability.scaling) return ability.scaling?.[0] || {};
    let best = ability.scaling[0];
    for (const tier of ability.scaling) {
      if (dtl >= tier.minDTL) best = tier;
    }
    return best;
  }

  canSeePlayer(game) {
    const player = game.player;
    const dx = player.x - this.x;
    const dy = player.y - this.y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist > 8) return false;

    // Check line of sight
    const line = this.getLine(this.x, this.y, player.x, player.y);
    for (const [lx, ly] of line) {
      const tile = game.map.get(`${lx},${ly}`);
      if (tile === 'wall') return false;
    }
    return true;
  }

  getLine(x0, y0, x1, y1) {
    const points = [];
    const dx = Math.abs(x1 - x0);
    const dy = Math.abs(y1 - y0);
    const sx = x0 < x1 ? 1 : -1;
    const sy = y0 < y1 ? 1 : -1;
    let err = dx - dy;

    let cx = x0, cy = y0;
    while (cx !== x1 || cy !== y1) {
      const e2 = 2 * err;
      if (e2 > -dy) { err -= dy; cx += sx; }
      if (e2 < dx) { err += dx; cy += sy; }
      points.push([cx, cy]);
    }
    return points;
  }

  doHunt(game) {
    const player = game.player;
    if (!player.alive) return;

    // Bump-to-attack if adjacent
    const dx = player.x - this.x;
    const dy = player.y - this.y;
    if (Math.abs(dx) <= 1 && Math.abs(dy) <= 1) {
      const result = game.combatSystem.attack(this, player, game);
      game.messageLog?.add(
        `${this.name} hits you for ${result.finalDamage}!`,
        '#ff0040'
      );
      return;
    }

    // Ranged attack ability
    for (const ability of this.abilities) {
      if (ability.name === 'Ranged Attack') {
        const scaling = this.getAbilityScaling(ability, game.dtl);
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist <= scaling.range && this.canSeePlayer(game)) {
          const result = game.combatSystem.attack(this, player, game);
          game.messageLog?.add(
            `${this.name} shoots you for ${result.finalDamage}!`,
            '#ff0040'
          );
          return;
        }
      }
    }

    // Pathfind toward player
    this.moveToward(player.x, player.y, game);
  }

  doPatrol(game) {
    if (this.canSeePlayer(game) || this.alerted) {
      this.behavior = 'hunt';
      this.doHunt(game);
      return;
    }
    this.doWander(game);
  }

  doWander(game) {
    if (this.canSeePlayer(game) || this.alerted) {
      this.behavior = 'hunt';
      this.doHunt(game);
      return;
    }

    // Random movement
    const dirs = DIRS[8];
    const dir = dirs[Math.floor(Math.random() * dirs.length)];
    const nx = this.x + dir[0];
    const ny = this.y + dir[1];
    this.tryMove(nx, ny, game);
  }

  doFlee(game) {
    const player = game.player;
    // Move away from player
    const dx = this.x - player.x;
    const dy = this.y - player.y;
    const len = Math.sqrt(dx * dx + dy * dy) || 1;
    const nx = this.x + Math.sign(dx);
    const ny = this.y + Math.sign(dy);
    if (!this.tryMove(nx, ny, game)) {
      this.doWander(game);
    }
  }

  doGuard(game) {
    const player = game.player;
    const dx = player.x - this.x;
    const dy = player.y - this.y;
    const dist = Math.sqrt(dx * dx + dy * dy);

    if (dist <= 1.5) {
      const result = game.combatSystem.attack(this, player, game);
      game.messageLog?.add(
        `${this.name} hits you for ${result.finalDamage}!`,
        '#ff0040'
      );
    }
  }

  moveToward(tx, ty, game) {
    // Simple A*-like movement
    const dx = tx - this.x;
    const dy = ty - this.y;
    const adx = Math.abs(dx);
    const ady = Math.abs(dy);

    // Try direct path first
    let nx = this.x + Math.sign(dx);
    let ny = this.y + Math.sign(dy);

    if (!this.tryMove(nx, ny, game)) {
      // Try horizontal
      if (adx > 0 && this.tryMove(this.x + Math.sign(dx), this.y, game)) return;
      // Try vertical
      if (ady > 0 && this.tryMove(this.x, this.y + Math.sign(dy), game)) return;
    }
  }

  tryMove(nx, ny, game) {
    const key = `${nx},${ny}`;
    const tile = game.map.get(key);
    if (!tile || tile === 'wall') return false;

    // Check if another monster is there
    if (game.getMonsterAt(nx, ny)) return false;

    // Check if player is there (don't move onto player, attack instead)
    if (game.player.x === nx && game.player.y === ny) return false;

    this.x = nx;
    this.y = ny;
    return true;
  }
}
