export const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    ROTATION_SPEED: 4,
    THRUST: 200,
    DRAG: 0.99,
    SHOOT_COOLDOWN: 0.2,
    RESPAWN_DELAY: 2.0,
    STARTING_LIVES: 3,
    ASTEROID_KILL_SCORE: 100,
    DESPAWN_DISTANCE: 1500,
    WAVE_DELAY: 1.0
};
