export const CONFIG = {
    SIM_WIDTH: 200,
    SIM_HEIGHT: 150,
    PIXEL_SIZE: 4,
    DEFAULT_BRUSH_SIZE: 3,
    MAX_BRUSH_SIZE: 10,
    PAINT_DENSITY: 0.7,
    FIRE_DEATH_CHANCE: 0.05,
    FIRE_SMOKE_CHANCE: 0.3,
    FIRE_RISE_CHANCE: 0.3,
    OIL_IGNITE_CHANCE: 0.5,
    PLANT_IGNITE_CHANCE: 0.2,
    WOOD_IGNITE_CHANCE: 0.05,
    STEAM_CONDENSE_CHANCE: 0.01,
    SMOKE_FADE_CHANCE: 0.02,
    PLANT_GROW_CHANCE: 0.02,
    ACID_DISSOLVE_CHANCE: 0.1
};
