export const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    PADDLE_WIDTH: 120,
    PADDLE_HEIGHT: 20,
    BALL_RADIUS: 8,
    INITIAL_SPEED: 400,
    MAX_SPEED: 800,
    SPEED_INCREMENT: 20,
    POWERUP_DROP_CHANCE: 0.15,
    POWERUP_FALL_SPEED: 150,
    WIDE_PADDLE_MULTIPLIER: 1.5,
    BRICK_HEIGHT: 25,
    BRICK_PADDING: 10
};
